#!/bin/bash

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

if [[ "$@" == *"--help"* ]]; then
    exec ls --help
fi

base=""
while read line; do
    if [ -z "$line" ]; then
        echo
        continue
    fi
    nocolor=$(echo $line | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")
    path=${nocolor##* }
    if [[ "$path" =~ ':'$ ]]; then
        base="${path::-1}/"
    fi
    perm=$(stat -c "%a" "$base$path" 2>/dev/null)
    if [ -n "$perm" ]; then
        printf "$perm "
    fi
    echo "$line"
done < <(ls "$@")
