#!/bin/bash

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

if [[ "$@" == *"--help"* ]]; then
    exec ls --help
fi

count=0
for arg in "$@"; do
    if [ -e "$arg" ]; then
        base="$arg"
        ((count++))
    fi
done

if [ "$count" -ne 1 ]; then
    base=""
fi

while read line; do
    if [ -z "$line" ]; then
        echo
        continue
    fi
    nocolor=$(echo "$line" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")
    path=${nocolor##* }
    if [[ "$path" =~ ':'$ ]]; then
        base="${path::-1}/"
    fi
    perm=$(stat -c "%a" "$base$path" 2>/dev/null)
    if [ -n "$perm" ]; then
        printf "%s" "$perm "
    fi
    echo "$line"
done < <(ls "$@")
