#!/bin/bash

if [ -n "$DEBUG" ]; then
    PS4=':${LINENO}+'
    set -x
fi

base=""
while read line; do
    if [ -z "$line" ]; then
        echo
        continue
    fi
    path=${line##* }
    if [[ "$path" =~ ':'$ ]]; then
        base="${path::-1}/"
    fi
    perm=$(stat -c "%a" "$base$path" 2>/dev/null)
    if [ -n "$perm" ]; then
        printf "$perm "
    fi
    echo "$line"
done < <(ls "$@")
